Change suggested Badlion Item Counter
proudmuslim-dev/proudmuslim.tech pull request #7
Opened 2021-05-22 14:54 UTC by DoKM

Changes the suggested Badlion Item Counter replacement mod from Sk1er's Patcher to DoKM's (me) Item Counter mod as it represents badlion's item counter feature more closely than patcher's.

https://hypixel.net/threads/1-8-9-item-counter-mod.3683685/

https://youtu.be/ZbKnewWrRbU

2021-05-22 22:25 UTC, proudmuslim-dev approved these changes

2021-05-22 22:25 UTC, proudmuslim-dev requested changes
Why not include both? I clicked on the wrong thing in my last review

2021-05-23 13:45 UTC, DoKM commented
Reverted the removal of the Sk1er Patcher link

2021-05-23 17:49 UTC, proudmuslim-dev approved these changes

2021-05-23 17:49 UTC, merged